name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          working_directory: 4-Rapport-Final
          root_file: 4-Rapport-Final.tex

      - name: PWD
        run: pwd && ls -lR

      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 4-Rapport-Final.pdf
          path: 4-Rapport-Final/4-Rapport-Final.pdf
