name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@1.0
        with:
            root_file: 4-Rapport-Final/4-Rapport-Final.tex 
