name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          working_directory: S2-APP7-rapport
          root_file: rapport-app7.tex

      - name: Upload artifact
        continue-on-error: true
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Rapport APP7 S2
          path: S2-APP7-rapport/rapport-app7.pdf
